import Head from "next/head";
import axios from "axios";
import { useEffect, useState } from "react";
import styles from "./index.module.scss";

const Home = () => {
 
 const [[days, hours, minutes], setTime] = useState([30, 60 , 60])

  const tick = () => {
    if(hours && minutes === 0) {
      setTime([days -1 , 23, 59])
    } else if(minutes === 0) {
      setTime([days, hours - 1 , 59])
    } else {
      setTime([days, hours, minutes -1])
    }
  }

  useEffect(() => {
    const timerId = setInterval(() => tick(), 60000)
    return () => clearInterval(timerId)
  })
  console.log([days,hours,minutes])
  console.log([minutes])
  return (
    <>
      <Head>
        <title>Honeycode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.eclipse1}></div>
      <div className={styles.launching_soon}>
        <h1>Launching Soon</h1>
      </div>
      <div className={styles.timer_container}>
        <div className={styles.countdown_container}>
          <div className={styles.glass_container}>
            <div className={styles.timer}></div>
            <div className={styles.timer}></div>
          </div>
          <h2>Days</h2>
        </div>

        <div className={styles.countdown_container}>
          <div className={styles.glass_container}>
            <div className={styles.timer}></div>
            <div className={styles.timer}></div>
          </div>
          <h2>Hours</h2>
        </div>

        <div className={styles.countdown_container}>
          <div className={styles.glass_container}>
            <div className={styles.timer}></div>
            <div className={styles.timer}></div>
          </div>
          <h2>Minutes</h2>
        </div>
      </div>
    </>
  );
};

export default Home;
